#!/bin/bash
cat 72.txt > allraw.txt
cat 73.txt >> allraw.txt
cat 74.txt >> allraw.txt
cat 75.txt >> allraw.txt
cat 76.txt >> allraw.txt
cat 77.txt >> allraw.txt
cat 78.txt >> allraw.txt
cat 80.txt >> allraw.txt
cat 81.txt >> allraw.txt
cat 82.txt >> allraw.txt
cat 83.txt >> allraw.txt
cat 84.txt >> allraw.txt
cat 85.txt >> allraw.txt
cat 86.txt >> allraw.txt
cat 87.txt >> allraw.txt
cat 88.txt >> allraw.txt
#cat 89.txt >> allraw.txt
#cat 90.txt >> allraw.txt
cat 91-in-SOD-format.txt >> allraw.txt
cat 92-in-SOD-format.txt >> allraw.txt
cat 93-in-SOD-format.txt >> allraw.txt
#cat 94.txt >> allraw.txt
cat 95.txt >> allraw.txt
